[package]
name = "garden-buttler"
version = "0.1.0"
authors = ["julise"]

[dependencies]
futures = "0.1"
tokio = "0.1.13"
tokio-signal = { version = "0.2.7" }
sysfs_gpio = { path = "../rust-sysfs-gpio", features = ["use_tokio"] }
