[package]
name = "garden-buttler"
version = "0.1.0"
authors = ["julise"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
sysfs_gpio = { version = "0.5", features = ["tokio"] }
ctrlc = { version = "3.1.1", features = ["termination"] }